### ISSUE TITLE
scsnowman  + LuaTeX-ja  で `! Undefined control sequence.` エラー

### ISSUE THREAD

**Issue by h-kitagawa** [aminophen/scsnowman.sty#12]
scsnowman 2023/02/14 v1.3b を LuaTeX-ja で使うと，次のエラーが発生します：
``` 
! Undefined control sequence.
l.181     \kansujichar
                    8="2603
?
```
1ヶ月前には出ていなかった覚えがあるので，びっくりしました．

edit: 最小ソース：
``` tex
\documentclass{minimal}
\usepackage{luatexja}
\usepackage{scsnowman}
\begin{document}
\end{document}
```

d7e4321e2d7736835a9d4ba70057d02c3ea838dc で変更された upTeX か否かの判定に LuaTeX-ja もパスしてしまうのが原因のようです．

**Comment by aminophen** [comment]
scsnowman → luatexja の順で読み込むと大丈夫なのでテストを素通りしていました。すみません。

8d26c880cf15c4e1ffc75b6b51ce97d9e088216f で良いでしょうか？

**Comment by h-kitagawa** [comment]
良さそうです，どうもありがとうございます．
