### ISSUE TITLE
newtxmath パッケージよりあとに読み込むとエラーになる

### ISSUE THREAD

**Issue by wtsnjp** [aminophen/scsnowman.sty#4]
タイトルの通りです．"Command \openbox already defined. Or name \end... illegal, see p.192 of the manual." と怒られます．原因を詳しく解析できていませんが，scsnowman-base.sty 内で amsthm パッケージを呼んでいるのが原因になっている模様です．

MWE:

```tex
\documentclass{article}

\usepackage{newtxmath}
\usepackage{scsnowman}

\begin{document}

foo

\end{document}
```

なお，newtxmath をあとに読み込んだ場合は問題ないように見えます．

**Comment by aminophen** [comment]
ありがとうございます。「\qed を変える機能を使う場合は amsthm を自分で読み込みましょう」ということで十分でしょうから，amsthm をデフォルトで読み込まないようにします。

（newtx… は，そういえば確か読込順序が大事でしたね。newtx… は ams… より後から読まないと，ams… が提供する新記号のフォントが変わらないのでした。）

**Comment by aminophen** [comment]
d98218e で amsthm を読み込まないようにしてみました。
