### ISSUE TITLE
Nose Option

### ISSUE THREAD

**Issue by yasunari** [aminophen/scsnowman.sty#7]
普段はLaTeXを使っていて，TeX言語に関しては学習中の初心者ですので，Pull requestではなくIssuesでの提案ということでお許し下さい。

雪だるまはかわいくて大好きなので，いつもscsnowmanパッケージにはお世話になっています。にんじん風の鼻を付けられるOptionがあると便利だと思うことが，よくあるので提案させて頂きました。

TeXCONF 2018には参加できると思います。お会いできるのを楽しみにしています。

**Comment by aminophen** [comment]
- 鼻
- 眉毛

くらいは構想はあったのですが，時間が取れず実装できていません…

**Comment by yasunari** [comment]
眉毛は，あったら面白そうですね。TeX言語をもっと勉強して，僕が実装できるくらいになりたいです。

**Comment by aminophen** [comment]
ご所望の形かどうかはわかりませんが，とりあえず nose オプションを作ってみました (f8f445a)。

<img width="465" alt="20180427-scsnowman-nose" src="https://user-images.githubusercontent.com/9957466/39368064-8e298cf0-4a73-11e8-83e4-8770a0c37270.png">

```` tex
\usepackage[svgnames]{xcolor}
\usepackage{scsnowman}
````
````
\scsnowman[hat=Green,muffler=Red,nose=Orange,arms=Brown,buttons=Blue,snow=LightBlue]
````

**Comment by yasunari** [comment]
ありがとうございます。
